carto_fiche_homepage_index:
    pattern: /
    defaults:
        _controller: CartoFicheBundle:Dashboard:index

carto_fiche_dashboard_dashboard:
    pattern: /dashboard
    defaults:
        _controller: CartoFicheBundle:Dashboard:dashboard

carto_fiche_categorie_index:
    path:     /categorie/
    defaults:
        _controller: CartoFicheBundle:Categorie:index

carto_fiche_categorie_new:
    path: /categorie/new
    defaults:
        _controller: CartoFicheBundle:Categorie:new

carto_fiche_categorie_create:
    pattern: /categorie/create
    defaults:
        _controller: CartoFicheBundle:Categorie:create

carto_fiche_categorie_edit:
    pattern: /categorie/edit/{id}
    defaults:
        _controller: CartoFicheBundle:Categorie:edit

carto_fiche_categorie_update:
    pattern: /categorie/update/{id}
    defaults:
        _controller: CartoFicheBundle:Categorie:update

carto_fiche_tag_show:
    pattern: /tag/show
    defaults:
        _controller: CartoFicheBundle:Tag:show

carto_fiche_tag_add:
    pattern: /tag/add
    defaults:
        _controller: CartoFicheBundle:Tag:add

carto_fiche_tag_edit:
    pattern: /tag/edit/{id}
    defaults:
        _controller: CartoFicheBundle:Tag:edit

carto_fiche_homepage:
    path:     /hello
    defaults: { _controller: CartoFicheBundle:Fiche:index }
